name: GKE CI/CD Pipeline Of Github Actions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build JARs and Docker Images
        run: |
          cd Backend
          for service in UserService ProductService CartService OrderService WalletService MailService TransactionService EurekaServer ApiGateway; do
            if [ -d "$service" ]; then
              cd $service
              chmod +x mvnw
              ./mvnw clean package -DskipTests
              lowercase_service=$(echo $service | tr '[:upper:]' '[:lower:]')
              docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/$lowercase_service:latest .
              docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$lowercase_service:latest
              cd ..
            else
              echo "Directory $service not found!"
              exit 1
            fi
          done

      - name: Get GKE Credentials
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "False"
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

      - name: Deploy to GKE
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "False"
        run: |
          kubectl apply -f Backend/k8s-manifests/ --validate=false
